apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../cluster/baseline
  - ../../cluster/hardening
  - ../../rbac/base
  - ../../network-security
  - ../../runtime-security
  - ../../supply-chain-security
  - ../../policy-engine
  - ../../observability-security
  - ../../multi-tenancy
